#!/usr/bin/env ansible-playbook
---
#
# valet.sh
#
# @author: "Johann Zelger"

- name: "tests"
  hosts: local
  gather_facts: True

  roles:
    - role: common

  tasks:

  - debug:
      msg: "{{ cli }}"
